app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', ['as' => 'home', 'uses' => 'WelcomeController@index']);

//Route::get('home', 'HomeController@index');

Route::get('about', 'AboutController@index');

Route::resource('lists', 'ListsController');

Route::resource('lists.tasks', 'TasksController');

Route::post('lists/{lists}/tasks/{tasks}/complete', 
	array('as' => 'complete_task', 'uses' => 'TasksController@complete'));

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

app/Http/Controllers/ListsController.php
<?php namespace Todoparrot\Http\Controllers;

use Todoparrot\Http\Requests;
use Todoparrot\Http\Controllers\Controller;

use Illuminate\Http\Request;

use Todoparrot\Todolist;
use Todoparrot\User;
use Todoparrot\Category;
use Todoparrot\Http\Requests\ListCreateFormRequest;

class ListsController extends Controller {

	public function __construct()
	{
		$this->middleware('auth');
		$this->middleware('listowner', ['only' => ['show', 'edit', 'update']]);
	}

	public function index()
	{
		$lists = User::find(\Auth::id())->lists()->orderBy('created_at', 'desc')->paginate(10);
		return view('lists.index')->withLists($lists);
	}

	/**
	* Presents the list creation form
	*
	*
	*/
	public function create()
	{
		$categories = \DB::table('categories')->lists('name', 'id');

		return view('lists.create')->with('categories', $categories);
	}

	/**
	 * Creates a new list
	 * @param  ListCreateFormRequest
	 * @return [type]
	 */
	public function store(ListCreateFormRequest $request)
	{

	    $list = new Todolist(array(
	      'name' => \Input::get('name'),
	      'description' => \Input::get('description')
	    ));

	    $list->category()->associate(Category::find(\Input::get('category')));

	    $user = User::find(\Auth::id());

	    $list = $user->lists()->save($list);

	    return \Redirect::route('lists.show', 
	    	array($list->id))->with('message', 'Your list has been created!');
	
	}

	/**
	 * Displays a specific list
	 * @param  integer $id The list ID
	 * @return Response
	 */
	public function show($id)
	{
		$list = Todolist::findOrFail($id);
		return view('lists.show')->withList($list);
	}

	/**
	 * Presents the list edit form
	 * @param  integer $id The list ID
	 * @return Response
	 */
	public function edit($id)
	{
        $list = Todolist::findOrFail($id);
        return view('lists.edit')->with('list', $list);
	}

	/**
	 * Update a list
	 * @param  integer $id The list ID
	 * @param  ListCreateFormRequest $request The form request object
	 * @return Response
	 */
	public function update($id, ListCreateFormRequest $request)
	{

        $user = \Auth::user();

        $list = Todolist::findOrFail($id);

        $list->update([
            'name' => $request->get('name'), 
            'description' => $request->get('description')
        ]);

        return \Redirect::route('lists.edit', 
            array($task->todolist->id))->with('message', 'Your list has been updated!');
 
	}

	/**
	 * Delete a list
	 * @param  integer $id The list ID
	 * @return Response
	 */
	public function destroy($id)
	{

        $user = \Auth::user();

        $list = Todolist::findOrFail($id);

        $list->delete();

        return \Redirect::route('lists.index')
            ->with('message', 'Task deleted!');


	}

}

resources/views/lists/create.blade.php
@extends('layouts.master')

@section('content')
<div class="col-md-6">
{!! Form::open(array('route' => 'lists.store', 'class' => 'form', 'novalidate' => 'novalidate')) !!}
    
<h2>Create a TODO List</h2>

@if (count($errors) > 0)
	<div class="alert alert-danger">
		There were some problems with your input.<br />
		<ul>
			@foreach ($errors->all() as $error)
				<li>{{ $error }}</li>
			@endforeach
		</ul>
	</div>
@endif
 
<div class="form-group">
    {!! Form::label('Your List Name') !!}
    {!! Form::text('name', null, array('required', 'class'=>'form-control', 'placeholder'=>'List Name')) !!}
</div>

<div class="form-group">
    {!! Form::label('List Category') !!}<br />
    {!! Form::select('category', array_merge(['0' => 'Select a Category'], $categories), null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('Your List Description') !!}
    {!! Form::textarea('description', null, array('class'=>'form-control', 'placeholder'=>'Enter a short description')) !!}
</div>
 
<div class="form-group">
    {!! Form::submit('Create List!', array('class'=>'btn btn-primary')) !!}
</div>
{!! Form::close() !!}
</div>

@endsection

resources/views/lists/edit.blade.php
@extends('layouts.master')

@section('content')
<div class="col-md-6">
{!! Form::model($list, array('method' => 'put', 'route' => ['lists.update', $list->id], 'class' => 'form')) !!}
    
<h2>Update a TODO List</h2>

@if (count($errors) > 0)
	<div class="alert alert-danger">
		There were some problems with your input.<br />
		<ul>
			@foreach ($errors->all() as $error)
				<li>{{ $error }}</li>
			@endforeach
		</ul>
	</div>
@endif
 
<div class="form-group">
    {!! Form::label('Your List Name') !!}
    {!! Form::text('name', null, array('required', 'class'=>'form-control', 'placeholder'=>'List Name')) !!}
</div>

<div class="form-group">
    {!! Form::label('Your List Description') !!}
    {!! Form::textarea('description', null, array('class'=>'form-control', 'placeholder'=>'Enter a short description')) !!}
</div>
 
<div class="form-group">
    {!! Form::submit('Update List!', array('class'=>'btn btn-primary')) !!}
</div>
{!! Form::close() !!}
</div>

@endsection

resources/views/lists/index.blade.php
@extends('layouts.master')

@section('content')

<div class="col-md-12">

  <p>
    <a href="/lists/create" class="btn btn-success">Create a New List</a>
  </p>

<h1>Your Lists</h1>

  @if (count($lists) > 0)

      <table class="table table-striped">
      <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Created On</th>
        <th>Remaining Tasks</th>
        <th></th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      @foreach ($lists as $list)

        <tr>
          <td>
            <a href="{{ URL::route('lists.show', $list->id) }}">{{ $list->name }}</a>
          </td>
          <td>
            {{ $list->description }}
          </td>
          <td>
            {{ date("F d, Y", strtotime($list->created_at)) }}
          </td>
          <td>
            {{ $list->remainingTasks() }} / {{ $list->tasks()->count() }}
          </td>
          <td>
            <a class="btn btn-success" href="{{ URL::route('lists.edit', $list->id) }}">Edit</a>
          </td>
          <td>
            {!! Form::open(array('route' => array('lists.destroy', $list->id), 'method' => 'delete')) !!}
              <button type="submit" class="btn btn-success" href="{{ URL::route('lists.destroy', $list->id) }}" title="Delete list">
              Delete
              </button>
            {!! Form::close() !!}
          </td>
        </tr>

      @endforeach
      </tbody>
      </table>

    {!! $lists->render() !!}

    @else
     <p>
      You haven't created any lists. No time like now! <a href="/lists/create">Create a list</a>
    </p>
    @endif

</div>

@endsection

resources/views/lists/show.blade.php
@extends('layouts.master')

@section('content')

<h1>{{ $list->name }}</h1>

<p>
Created on: {{ date('F d, Y', strtotime($list->created_at)) }} <br />
Last modified: {{ date('F d, Y', strtotime($list->updated_at)) }}<br />
{{ $list->description }}
</p>

<h2>Tasks</h2>

<p>
<a href="{{ URL::route('lists.tasks.create', $list->id) }}" class='btn btn-primary'>Add a task</a>
</p>

@if($list->tasks->count() == 0)

<p>
No tasks assigned to this list. <a href="/lists/{{$list->id}}/tasks/create">Add a task</a>.
</p>

@else

  <div class="table-responsive">
    <table class="table table-striped">
      @foreach ($list->tasks as $task)      
      <tr>
        <td>
        @if($task->done)
          <del><a href="{{ URL::route('lists.tasks.edit', [$list->id, $task->id]) }}">{{ $task->name }}</a></del>
        @else
          <a href="{{ URL::route('lists.tasks.edit', [$list->id, $task->id]) }}">{{ $task->name }}</a>
        @endif
        </td>
        <td style="text-align: right;">

          <div style="float: right; padding-right: 5px;">
            {!! Form::open(array('route' => array('lists.tasks.destroy', $list->id, $task->id), 'method' => 'delete')) !!}
                  <button type="submit" href="{{ URL::route('lists.tasks.destroy', [$list->id, $task->id]) }}" class="glyphicon glyphicon-remove" title="Delete task"></button>
              {!! Form::close() !!}
          </div>

          <div style="float: right; padding-right: 5px;">
              {!! Form::open(array('route' => array('complete_task', $list->id, $task->id), 'method' => 'post')) !!}

                  @if($task->done)
                  <button type="submit" href="{{ URL::route('complete_task', [$list->id, $task->id]) }}" class="glyphicon glyphicon-repeat" title="Mark Incomplete"></button>
                  @else
                  <button type="submit" href="{{ URL::route('complete_task', [$list->id, $task->id]) }}" class="glyphicon glyphicon-ok" title="Mark complete"></button>
                  @endif
              {!! Form::close() !!}
          </div>

          <div style="float: right; padding-right: 5px;">
          {!! Form::open(array('route' => array('lists.tasks.edit', $list->id, $task->id), 'method' => 'get')) !!}
                  <button type="submit" href="{{ URL::route('lists.tasks.edit', [$list->id, $task->id]) }}" class="glyphicon glyphicon-pencil" title="Edit Task"></button>
              {!! Form::close() !!}
          </div>

        </td>
      </tr>
      @endforeach
    </table>
  </div>

@endif

@endsection